name: utils_nfcore_abotyper_pipeline
description: Subworkflow with functionality specific to the nf-core/abotyper pipeline
keywords:
  - utility
  - pipeline
  - initialisation
  - validation
  - abo
  - blood_typing
components:
  - UTILS_NFSCHEMA_PLUGIN
  - UTILS_NFCORE_PIPELINE
  - UTILS_NEXTFLOW_PIPELINE
  - samplesheetToList
workflows:
  - PIPELINE_INITIALISATION
  - PIPELINE_COMPLETION
input:
  - version:
      type: boolean
      description: Display version and exit
  - validate_params:
      type: boolean
      description: Boolean whether to validate parameters against the schema at runtime
  - monochrome_logs:
      type: boolean
      description: Do not use coloured log outputs
  - nextflow_cli_args:
      type: array
      description: List of positional nextflow CLI args
  - outdir:
      type: string
      description: The output directory where the results will be saved
  - input:
      type: string
      description: Path to input samplesheet
  - email:
      type: string
      description: Email address for completion notification
  - email_on_fail:
      type: string
      description: Email address sent on pipeline failure
  - plaintext_email:
      type: boolean
      description: Send plain-text email instead of HTML
  - hook_url:
      type: string
      description: Hook URL for notifications
  - multiqc_report:
      type: string
      description: Path to MultiQC report
output:
  - samplesheet:
      type: channel
      description: Channel containing samplesheet data
  - versions:
      type: channel
      description: Channel containing software versions
authors:
  - "@fmobegi"
maintainers:
  - "@fmobegi"